on:
  workflow_call:
    inputs:
      deployTo:
        description: Directory where to deploy to (if empty that home dir is used)
        type: string
        required: false
      ecosystemFile:
        description: Override for which file to use for ecosystem.config.js
        type: string
        required: false
        default: 'ecosystem.config.js'
      applicationSuffixId:
        description: Suffix id for the application (set to 1 for 1st application, 2 for 2nd, etc)
        type: string
        required: true
      environment:
        description: The github environment to inherit secrets from
        type: string
        required: true
      additionalEnv:
        description: Additional environment variables to append to the .env file (be sure to escape double-quotes)
        type: string
        required: false

jobs:
  build-artifact:
    name: Build deployment artifact
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('yarn.lock') }}-
      - name: Dependencies
        run: yarn install --frozen-lockfile --immutable
      - name: Build
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          touch .env
          echo "${{ inputs.additionalEnv }}" >> .env
          echo $(node -v)
          NEXT_PRIVATE_STANDALONE=1 yarn build
          sed -i '/server.listen(currentPort, (err) => {/c\server.listen(currentPort, process.env.VHOSTIP || "0.0.0.0", (err) => {' .next/standalone/server.js
          cp -R public .next/standalone/public
          cp ecosystem.config.js .next/standalone/
          cp ${{ inputs.ecosystemFile }} .next/standalone/
          cp -R .next/static .next/standalone/.next/static
          tar -czf "${GITHUB_SHA}_${{ inputs.applicationSuffixId }}".tar.gz -C .next/standalone .
      - name: Node version
        run: echo "$(node -v)"
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-artifact
          path: ${{ github.sha }}_${{ inputs.applicationSuffixId }}.tar.gz
