on:
  workflow_call:
    inputs:
      applicationSuffixId:
        description: Suffix id for the application (set to 1 for 1st application, 2 for 2nd, etc)
        type: string
        required: false
      environment:
        description: The github environment to inherit secrets from
        type: string
        required: true
      serverHost:
        type: string
        required: true
      serverPort:
        type: string
        required: true
      serverUser:
        type: string
        required: true

jobs:
  activate-artifact:
    name: Upload and activate artifact
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: deployment-artifact
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ inputs.serverHost }}
          username: ${{ inputs.serverUser }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ inputs.serverPort }}
          source: ${{ github.sha }}_${{ inputs.applicationSuffixId }}.tar.gz
          target: ./artifacts
      - name: Node version
        run: echo "$(node -v)"
        shell: bash
      - name: Activate
        uses: appleboy/ssh-action@master
        env:
          GITHUB_SHA: ${{ github.sha }}
        with:
          host: ${{ inputs.serverHost }}
          username: ${{ inputs.serverUser }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ inputs.serverPort }}
          source: ${{ github.sha }}_${{ inputs.applicationSuffixId }}.tar.gz
          target: ./artifacts
          envs: GITHUB_SHA,DOMAIN
          script_stop: true
          script: |
            echo $(node -v)
            release_folder=$(date +%Y%m%d%H%I%S)
            mkdir -p ./graphcommerce${{ inputs.applicationSuffixId }}/releases/$release_folder
            tar xzf ./artifacts/${GITHUB_SHA}_${{ inputs.applicationSuffixId }}.tar.gz -C ./graphcommerce${{ inputs.applicationSuffixId }}/releases/$release_folder
            rm -rf ./artifacts/${GITHUB_SHA}_${{ inputs.applicationSuffixId }}.tar.gz
            ln -s releases/$release_folder releases/current
            mv ./graphcommerce${{ inputs.applicationSuffixId }}/releases/current ./graphcommerce${{ inputs.applicationSuffixId }}/
            ls -x1 ./graphcommerce${{ inputs.applicationSuffixId }}/releases/ | head -n -3 | xargs -d '\n' rm -rf